# -*- coding: utf-8 -*-
"""ESAA YB 1주차 과제 (1) _ 2593136 박희원

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3dya4zwdVzev1zsvQCUSCOR97ovvXr6
"""



"""# 03. 넘파이


*   머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다.
Numerical Python을 의미하는 넘파이(Numpy)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지이다.
루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장한다.
대량 데이터 기반의 과학과 공학 프로그램은 빠른 계산 능력이 매우 중요하므로 파이썬 기반의 많은 과학과 공학 패키지는 넘파이에 의존한다.
*   넘파이는 또한 C/C++과 같은 저수준 언어 기반의 호환 API를 제공한다. 넘파이는 매우 빠른 배열 연산을 보장해주지만, 파이썬 언어 자체가 가지는 수행 성능의 제약이 있으므로 C/C++ 기반의 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 쉽게 통합할 수 있다.
*   많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으므로, 이들 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용한다.

### 넘파이 ndarray 개요

가장 먼저 넘파이 모듈을 임포트한다. 새로운 주피터 노트북을 생성하고 맨 위의
셀에 다음과 같이 입력한다.

"""

import numpy as np

"""물론 import numpy만 해도 충분하지만, as np를 추가해 약어로 모듈을 표현해주는 게 관례이다.


*   넘파이의 기반 데이터 타입은 ndarray이며, 이를 이용해 넘파이에서 다차원(Multi-dimension) 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.
*   넘파이 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행한다. 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있다.


"""

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

"""

*   np.array() 사용법은 간단하다. ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환한다. ndarray.shape는 ndarray의 차원과 크기를 튜플(tuple)의 형태로 반환해준다.

[1, 2, 3]인 array1의 shape는 (3,)인데, 이는 1차원 array로 3개의 데이터를 가지고 있음을 뜻한다.
[[1, 2, 3], [2, 3, 4]]인 array2의 shape는 (2, 3)인데, 이는 2차원 array로, 2개의 로우와 3개의 칼럼으로 구성되어 2 * 3 = 6개의 데이터를 가지고 있음을 뜻한다.
[[1, 2, 3]]인 array3의 경우 shape는 (1, 3)이며, 이는 1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터를 의미한다.


*   array3는 array1과 동일한 데이터 건수를 가지고 있으나, array1은 명확히 1차원임을 (3,) 형태로 표현한 것이며, array3 역시 로우와 칼럼으로 이뤄진 2차원 데이터임을 (1, 3)으로 표현한 것이다. 이 차이를 이해하는 것은 매우 중요한데, 머신러닝 알고리즘과 데이터 세트 간의 입출력과 변환을 수행하다 보면 명확히 1차원 데이터 또는 다차원 데이터를 요구하는 경우가 있다. 분명히 데이터 값으로는 서로 동일하나 차원이 달라 오류가 발생하는 경우가 빈번하므로 명확히 차원의 차수를 변환하는 방법을 알아야 한다.
*   각 array의 차원을 ndarray.ndim을 이용해 확인한다.



"""

print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

"""

*   array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용된다. 리스트 []는 1차원이고, 리스트의 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있기 때문이다.

### ndarray의 데이터 타입



*   ndarray 내의 데이터값은 숫자값, 문자열값, 불값 등이 모두 가능하다. 숫자형의 경우 int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), 그리고 이보다 더 큰 숫자 값이나 정밀도를 위해 complex 타입도 제공한다.
*   ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다. 즉, 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없다. ndarray 내의 데이터 타입은 dtype 속성으로 확인할 수 있다.



"""

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

"""

*   서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하며, 만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형변환을 일괄적으로 적용한다.
"""

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

"""int형 값과 문자열이 섞여있는 list2를 ndarray로 변환한 array2는 숫자형 값 1, 2가 모두 문자열 값인 '1', '2'로 변환됐다. (int형이 유니코드 문자열 값으로 변환됐다.)
int형과 float형이 섞여있는 list3의 경우에도 int 1, 2가 모두 1. 2.인 float 64형으로 변환됐다.


*   ndarray 내 데이터값의 타입 변경도 astype() 메서드를 이용해 할 수 있다. astype()에 인자로 원하는 타입을 문자열로 지정하면 된다. 이렇게 데이터 타입을 변경하는 경우에는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데 메모리를 더 절약해야 할 때 보통 이용된다. 대용량의 데이터를 로딩할 때는 수행속도가 느려지거나 메모리 부족으로 오류가 발생할 수 있기 때문이다.

"""

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

"""### ndarray를 편리하게 생성하기 - arange, zeros, ones



*   특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 있다. 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우가 그 예이다.
*   arange()는 파이썬 표준 함수인 range()와 유사한 기능을 한다. 쉽게 생각하면 array를 range()로 표현하는 것이다. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다.

"""

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

"""default 함수 인자는 stop 값이며, 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어준다. 여기서는 stop값만 부여했으나 range와 유사하게 start 값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있다.


*   zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환한다.
*   ones()도 유사하게 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다. 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다.


"""

zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

"""### ndarray의 차원과 크기를 변경하는 reshape()



*   reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환한다. 변환을 원하는 크기를 함수 인자로 부여하면 된다.



"""

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

"""

*   reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생시킨다. 가령 (10,) 데이터를 (4,3) Shape 형태로 변경할 수는 없는 것이다.

"""

array1.reshape(4, 3)

"""

*   reshape()를 실전에서 더욱 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우일 것이다. -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다. 물론 -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다.

"""

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

"""

*   -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용된다. reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨을 보장한다. 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용된다.
*   ndarray는 tolist() 메서드를 이용해 리스트 자료형으로 변환할 수 있다.

"""

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape:', array6.shape)

"""### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)


*   인덱싱이란 넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 하는 것이다.




1.   특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.
2.   슬라이싱(Slicing): 연속된 인덱스상의 ndarray를 추출하는 방식으로, ':' 기호 사이에 시작 인덱스와 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환한다. 예를 들어, 1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환하는 것이다.
3.   팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.
4.   불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다.



*   단일 값 추출을 위해서는 ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력하면 된다.

"""

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

"""이 때 array1[2]의 타입은 더 이상 ndarray 타입이 아닌 ndarray 내의 데이터값을 의미한다.

*   인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있다. 인덱스 -1은 맨 뒤의 데이터값을 의미하고, -2는 맨 뒤에서 두 번째에 있는 데이터값이다.


"""

print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

"""

*   단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정할 수 있다.

"""

array1[0] = 9
array1[8] = 0
print('array1:', array1)

"""

*   다차원 ndarray에서 단일 값을 추출할 때, 3차원 이상의 ndarray에서의 데이터 추출은 2차원 ndarray와 큰 차이가 없다. 1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것이다.

"""

# 1차원 ndarray를 2차원 3 x 3 ndarray로 변환 후, [row, col]을 이용해 2차원 ndarray에서의 데이터 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

"""

*   넘파이의 다차원 ndarray는 axis 구분을 가진다. axis 0은 로우 방향의 축을 의미하고, axis 1은 칼럼 방향의 축을 의미한다. 정확히 얘기하자면, 앞 설명에서 지칭한 로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 방식이다. 이해를 돕기 위해 로우, 칼럼 형식으로 표현한 것일 뿐 정확한 표현은 axis 0, axis 1이 맞다. 즉 [row=0, col=1] 인덱싱은 [axis0=0, axis1=1]이 정확한 표현이다. 2차원이므로 axis 0, axis 1로 구분되는 것이며 3차원 ndarray의 경우에는 axis 0, axis 1, axis 2로 3개의 축을 가지게 된다. (행, 열, 높이로 이해하면 된다.)
*   슬라이싱은 ':' 기호를 이용해 연속한 데이터를 추출하는 기능이다. 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입이다. ':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1의 위치에 있는 데이터의 ndarray를 반환한다.
"""

array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

"""

*   슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능하다. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주하고, ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주한다. 또, ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다.

"""

array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

"""

*   2차원 ndarray에서 슬라이싱으로 데이터에 접근할 때는 1차원 ndarray에서의 슬라이싱과 유사하며, 단지 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다르다.

"""

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

"""

*   2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다. 즉, array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면 로우 축(axis 0)의 첫번째 로우 ndarray를 반환하게 되는 것이다. 반환되는 ndarray는 1차원이다. 마찬가지로 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환한다.

"""

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

"""

*   팬시 인덱싱(Fancy Indexing)은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다.

"""

# 2차원 ndarray에 팬시 인덱싱 적용
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

"""

*   불린 인덱싱(Boolean indexing)은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용된다. 불린 인덱싱을 이용하면 for loop/if else 문보다 훨씬 간단하게 조건 필터링을 할 수 있다. ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하기만 하면 된다.

"""

array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값: ', array3)

array1d > 5

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ', array3)

indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

"""

*   불링 인덱싱이 동작하는 단계는 다음과 같다. (i) array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재한다. (ii) False 값은 무시하고 True 값에 해당하는 인덱스값만 저장한다. 이 때 유의할 점은, True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것이다. (iii) 저장된 인덱스 데이터 세트로 ndarray를 조회한다.

### 행렬의 정렬 - sort()와 argsort()



*   넘파이의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식이 있고, ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있다. 전자의 경우 원 행렬은 그대로 유지한 채로 원 행렬의 정렬된 행렬을 반환하며, 후자의 경우에는 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None이다.




"""

org_array = np.array([3, 1, 9, 5])
print('원본 행렬: ', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

"""

*   np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬한다. 내림차순으로 정렬하기 위해서는 [::-1]을 적용한다. np.sort()[::-1]과 같이 사용하면 된다.

"""

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

"""

*   행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 로우 방향 또는 칼럼 방향으로 정렬을 수행할 수 있다.

"""

array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

"""

*   원본 행렬이 정렬되었을 떄 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 수 있다. 이 때 np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환한다. 오름차순이 아닌 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1]을 적용하면 된다."""

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

"""

*   argsort()는 넘파이에서 활용도가 매우 높다. 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없어, 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 한다. 예를 들어, 학생별로 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 각각 ndarray로 가져야 한다. 즉 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 활용하고자 한다면 name_array=['John', 'Mike', 'Sarah', 'Kate', 'Samuel']와 score_array=[78, 95, 84, 98, 88]과 같이 2개의 ndarray를 만들어야 한다. 이때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있다.
*   항목 추가

"""

import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력: ', name_array[sort_indices_asc])

"""### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기



*   행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능하다. 두 행렬 A와 B의 내적은 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값이다. 행렬 내적은 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일하여야 내적 연산이 가능하다.


"""

A = np.array( [[1, 2, 3],
               [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과: \n', dot_product)

"""

*   원 행렬에서 행과 열 위치를 교환한 원소로 궝한 행렬을 그 행렬의 전치 행렬이라고 한다. 즉 2 x 2 행렬 A가 있을 경우 A 행렬의 1행 2열의 원소를 2행 1열의 원소로, 2행 1열의 원소를 1행 2열의 원소로 교환하는 것이다. 행렬 A의 전치 행렬은 A^T와 같이 표기한다. 넘파이의 transpose()를 이용해 전치 행렬을 쉽게 구할 수 있다.

"""

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)